[carbon]


[carbon.rsf]
rsf = 1.00

[carbon.models]
6peaks = "A+B+C+D+E+F"
6peaks_sv = "Asv+B+C+D+E+F"
6peaks_la = "Ala+B+C+D+E+F"
6peaks_lag = "Alag+B+C+D+E+F"


[carbon.peaks]


[carbon.peaks.A]
docstring ="""
C=C (sp2 carbon)
"""
peak_name = "A"
peak_type = "Voigt"
[carbon.peaks.A.param_hints]
center = {value = 284.3, min = 284.2, max = 284.6}
amplitude = {value = 160000, min = 100, max = 5e5}
sigma = {value = 0.68, min = 0.1, max = 3}
gamma = {value = 0.16, min = 0.05, max = 3}
fwhm = {value = 0.7, min = 0.3, max = 0.9}


[carbon.peaks.Asv]
docstring ="""
C=C (sp2 carbon)
"""
peak_name = "Asv"
peak_type = "SkewedVoigt"
[carbon.peaks.Asv.param_hints]
center = {value = 284.3, min = 284.2, max = 284.6}
amplitude = {value = 160000, min = 100, max = 5e5}
sigma = {value = 0.68, min = 0.1, max = 1}
gamma = {value = 0.16, min = 0.05, max = 0.6}
fwhm = {value = 0.7, min = 0.3, max = 0.9}
skew = {value = 0, min = 0, max = 1000}


[carbon.peaks.Ala]
docstring ="""
C=C (sp2 carbon)
"""
peak_name = "Ala"
peak_type = "LA"
[carbon.peaks.Ala.param_hints]
center = {value = 284.5, min = 284.2, max = 284.6}
amplitude = {value = 160000, min = 100, max = 5e5}
alpha = {value = 2.5, min = 2.3, max = 2.6}
beta = {value = 1.2, min = 1, max = 1.4}
fwhm = {value = 0.7, min = 0.3, max = 3.5}


[carbon.peaks.B]
docstring ="""
C-C, C-H (sp3 carbon)
"""
peak_name = "B"
peak_type = "Voigt"
[carbon.peaks.B.param_hints]
shift = {value = 0.3, min = 0.2, max = 0.7}
sp2_peak = {value = 284.5}
center = {expr = 'B_sp2_peak + B_shift'}
amplitude = {value = 133000, min = 100, max = 7e5}
sigma = {value = 0.68, min = 0.1, max = 3}
gamma = {value = 0.16, min = 0.05, max = 3}
fwhm = {value = 1.2, min = 0.5, max = 2.5}
mix = {value = 0.3, min = 0.15, max = 0.35}


[carbon.peaks.C]
docstring ="""
C-O-C, C-OH
"""
peak_name = "C"
peak_type = "Voigt"
[carbon.peaks.C.param_hints]
shift = {value = 1.7, min = 1.5, max = 1.9}
sp2_peak = {value = 284.5}
center = {expr = 'C_sp2_peak + C_shift'}
amplitude = {value = 26000, min = 100, max = 7e5}
sigma = {value = 0.68, min = 0.1, max = 3}
gamma = {value = 0.16, min = 0.05, max = 3}
fwhm = {value = 1.8, min = 0.5, max = 3.5}


[carbon.peaks.D]
docstring = """
C=O
"""
peak_name = "D"
peak_type = "Voigt"
[carbon.peaks.D.param_hints]
shift = {value = 3.5, min = 3.2, max = 3.8}
sp2_peak = {value = 284.5}
center = {expr = 'D_sp2_peak + D_shift'}
amplitude = {value = 12500, min = 100, max = 4e5}
sigma = {value = 0.68, min = 0.1, max = 3}
gamma = {value = 0.16, min = 0.05, max = 3}
fwhm = {value = 1.8, min = 0.5, max = 3.5}


[carbon.peaks.E]
docstring ="""
O-C=O
"""
peak_name = "E"
peak_type = "Voigt"
[carbon.peaks.E.param_hints]
shift = {value = 4.5, min = 4.1, max = 4.9}
sp2_peak = {value = 284.5}
center = {expr = 'E_sp2_peak + E_shift'}
amplitude = {value = 12500, min = 100, max = 4e5}
sigma = {value = 0.68, min = 0.1, max = 3}
gamma = {value = 0.16, min = 0.05, max = 3}
fwhm = {value = 1.8, min = 0.5, max = 3.5}


[carbon.peaks.F]
docstring ="""
π-π* satellite
"""
peak_name = "F"
peak_type = "Voigt"
[carbon.peaks.F.param_hints]
shift = {value = 6.41, min = 5.8, max = 6.5}
sp2_peak = {value = 284.5}
center = {expr = 'F_sp2_peak + F_shift'}
amp_ratio = {value = 0.06963, min = 0.065, max = 0.075}
amplitude = {value = 8200, min = 100, max = 2e5}
sigma = {value = 0.68, min = 0.1, max = 3}
gamma = {value = 0.16, min = 0.05, max = 3}
fwhm = {value = 2.7, min = 2.2, max = 2.9}
mix = {value = 0.3, min = 0.1, max = 0.8}


[oxygen]


[oxygen.rsf]
rsf = 2.88

[oxygen.models]
4peaks = "A+B+C+D"
3peaks = "A+B+D"
2peaks = "A+B"

[oxygen.peaks.A]
docstring = """
C=O
"""
peak_name = "A"
peak_type = "Voigt"
[oxygen.peaks.A.param_hints]
center = {value = 532, min = 531.5, max = 532.4}
amplitude = {value = 22000, min = 100, max = 5e5}
sigma = {value = 0.68, min = 0.1, max = 1}
gamma = {value = 0.16, min = 0.05, max = 0.6}
fwhm = {value = 1.8, min = 0.5, max = 3.5}
mix = {value = 0.2, min = 0.01, max = 1}

[oxygen.peaks.B]
docstring = """
C-O
"""
peak_name = "B"
peak_type = "Voigt"
[oxygen.peaks.B.param_hints]
center = {value = 533, min = 532.8, max = 534}
amplitude = {value = 15000, min = 100, max = 5e5}
sigma = {value = 0.68, min = 0.1, max = 1}
gamma = {value = 0.16, min = 0.05, max = 0.6}
fwhm = {value = 1.8, min = 0.5, max = 3.5}
mix = {value = 0.2, min = 0.01, max = 1}


[oxygen.peaks.C]
docstring = """
C=O (aromatic)
"""
peak_name = "C"
peak_type = "Voigt"
[oxygen.peaks.C.param_hints]
center = {value = 530.9, min = 530.4, max = 531.3}
amplitude = {value = 12000, min = 100, max = 5e5}
sigma = {value = 0.68, min = 0.1, max = 1}
gamma = {value = 0.16, min = 0.05, max = 0.6}
fwhm = {value = 1.8, min = 0.5, max = 3.5}
mix = {value = 0.2, min = 0.01, max = 1}


[oxygen.peaks.D]
docstring = """
other
"""
peak_name = "D"
peak_type = "Voigt"
[oxygen.peaks.D.param_hints]
center = {value = 535.5, min = 534, max = 536}
amplitude = {value = 6600, min = 100, max = 2e4}
sigma = {value = 0.68, min = 0.1, max = 1}
gamma = {value = 0.16, min = 0.05, max = 0.6}
fwhm = {value = 1.8, min = 0.5, max = 3.5}
mix = {value = 0.2, min = 0.01, max = 1}